# Generated by Django 3.2.13 on 2022-06-24 08:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20220624_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='happiness_rating',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='productivity_rating',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(fields=('user', 'day'), name='unique_entry_day'),
        ),
    ]
