# Generated by Django 4.0.4 on 2022-07-08 05:06

from django.db import migrations

def create_inital_data(apps, schema_editor):

    apps.get_model('diary', 'Repo').objects.create(name='Atikon-DB').save()
    apps.get_model('diary', 'Repo').objects.create(name='Atikon-Intranet').save()
    apps.get_model('diary', 'Repo').objects.create(name='CMS').save()
    apps.get_model('diary', 'Repo').objects.create(name='Onlinetools').save()
    apps.get_model('diary', 'Repo').objects.create(name='mein-Atikon').save()
    apps.get_model('diary', 'Repo').objects.create(name='Atikon-API').save()

    apps.get_model('diary', 'Techstack').objects.create(name='Perl').save()
    apps.get_model('diary', 'Techstack').objects.create(name='Python').save()
    apps.get_model('diary', 'Techstack').objects.create(name='Raku').save()
    apps.get_model('diary', 'Techstack').objects.create(name='JavaScript').save()
    apps.get_model('diary', 'Techstack').objects.create(name='CSS').save()
    apps.get_model('diary', 'Techstack').objects.create(name='PostgreSQL').save()
    apps.get_model('diary', 'Techstack').objects.create(name='puppet').save()

    apps.get_model('diary', 'IncidentTag').objects.create(name='Systemcrash').save()
    apps.get_model('diary', 'IncidentTag').objects.create(name='Knowledge gap').save()

class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_incident_created_at'),
    ]

    operations = [
        migrations.RunPython(create_inital_data)
    ]
