# Generated by Django 3.2.13 on 2022-07-26 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_entry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='happiness_rating',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='incidents',
            field=models.ManyToManyField(blank=True, to='diary.Incident'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='productivity_rating',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='meltdown_rating',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='incident',
            name='repos',
            field=models.ManyToManyField(blank=True, to='diary.Repo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='tags',
            field=models.ManyToManyField(blank=True, to='diary.IncidentTag'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='techstack',
            field=models.ManyToManyField(blank=True, to='diary.Techstack'),
        ),
    ]
